### ISSUE TITLE
Framebuffer not resizing

### ISSUE THREAD

**Issue by Craft4Cube** [shinyhut/vernacular-vnc#1]
For some reason the framebuffer/Image is not the same size as on the remote. It always stays the same as it was when it was initialized.

**Comment by shinyhut** [comment]
@Craft4Cube do you mean the screen resolution was changed on the remote host during the session? Was the local framebuffer the correct size at the start of the session, or was it always the wrong size?

**Comment by Craft4Cube** [comment]
It was correct when the session was started. When it changed in the remote,
the client didn't resize.

shinyhut <notifications@github.com> schrieb am Mi., 25. Apr. 2018, 14:44:

**Comment by shinyhut** [comment]
Ok. There is a VNC extension called 'DesktopSize' which adds support for changing the remote screen size during a session, but Vernacular doesn't currently support it. I'll have a go at implementing it - can you let me know which VNC server you're using?

**Comment by Craft4Cube** [comment]
Im using the one integrated into qemu

shinyhut <notifications@github.com> schrieb am Mi., 25. Apr. 2018, 17:58:

**Comment by shinyhut** [comment]
@Craft4Cube can you try this branch:

https://github.com/shinyhut/vernacular-vnc/tree/feature/DesktopSize

I've tested it with qemu's integrated VNC server and TightVNC as a standalone server.

**Comment by Craft4Cube** [comment]
Thank you, it's working perfectly. :+1:

**Comment by shinyhut** [comment]
Thanks. This was fixed in [976ffaa](https://github.com/shinyhut/vernacular-vnc/commit/976ffaa734b3fe1130f1aa503d07f61ee5ac5c06) and released as [v1.1.0](https://github.com/shinyhut/vernacular-vnc/releases/tag/v1.1.0)
