### ISSUE TITLE
Sending Pressed events not always works

### ISSUE THREAD

**Issue by Meister1593** [shinyhut/vernacular-vnc#10]
Hi. I was debugging strange behavior of VNC input handling in one Minecraft Mod called [MCVMComputers](https://github.com/Delta2Force/MCVmComputers) with experimental usage of Qemu virtual machine.
Author of this mod chose to use VNC with this library for graphics and input handling.
Not entirely sure, if bug was because of Vernacular of because of mod, but i've checked everything about input handling, and thing what i think is glitching is Vernacular.

In this mod, you can place screens, computers and etc, then you boot them as usual VM. When you right click on screen, you lock onto it you can type and move mouse.
Back to the bug, input handling start executing wrong key events after GUI is locked on the screen for second time, even if keysums that client sends (code snippet bellow) are the same. 
Keys are updated in another thread and it looks like [this](https://github.com/Meister1593/MCVmComputers/blob/e326d8336810f88490c5a008e132ea180ef9163b/src/main/java/mcvmcomputers/client/utils/VMRunnable.java#L74-L78)

This mod uses `VernacularClient.updateKey(keySum, pressed)` method for updating each keypress.

[Qemu issue where all development about it goes](https://github.com/Delta2Force/MCVmComputers/issues/53)
[Conversion of GLFW game characters to VNC](https://github.com/Meister1593/MCVmComputers/blob/e326d8336810f88490c5a008e132ea180ef9163b/src/main/java/mcvmcomputers/client/utils/KeyConverter.java#L241-L516)
[Adding new keypressed to later VNC send](https://github.com/Meister1593/MCVmComputers/blob/e326d8336810f88490c5a008e132ea180ef9163b/src/main/java/mcvmcomputers/mixins/KeyboardMixin.java#L33)
Ask me about any info you need to debug, i have full debugging workflow settled up for this and i really want to fix this.

**Comment by shinyhut** [comment]
Hi @Meister1593, I've had a quick look and the only thing that jumps out at me is your `ClientMod.qemuKeys` is an `ArrayList`, which isn't thread safe. As you're adding and removing key events to and from it in different threads, that could result in the contents being corrupted. Does redefining it with something list  `public static List<QemuKey> qemuKeys = Collections.synchronizedList(new ArrayList<>());` help? If not, I'll have a better look later, as this is an interesting project so I'd like to see it working.

**Comment by Meister1593** [comment]
> Hi @Meister1593, I've had a quick look and the only thing that jumps out at me is your `ClientMod.qemuKeys` is an `ArrayList`, which isn't thread safe. As you're adding and removing key events to and from it in different threads, that could result in the contents being corrupted. Does redefining it with something list `public static List<QemuKey> qemuKeys = Collections.synchronizedList(new ArrayList<>());` help? If not, I'll have a better look later, as this is an interesting project so I'd like to see it working.

VMRunnable is itself like a singleton, it should be only one at the time and run in while loop outside game loop continuously.
Problem isn't with thread safety of ArrayList, i checked that after adding to qemuKeys in processes in in VMRunnable just fine.

**Comment by Meister1593** [comment]
I've tried making synchronized list, it didn't help (since it's not a  problem with thread safety)

**Comment by Meister1593** [comment]
No problem viewing through external vnc viewer (tigervnc), so it's not qemu internal vnc issue for sure.

**Comment by Meister1593** [comment]
I have a clue. It seems that author did not make sure that key is unpressed and they stuck being pressed forever.

**Comment by Meister1593** [comment]
> I have a clue. It seems that author did not make sure that key is unpressed and they stuck being pressed forever.

It was the issue. The input handling was really weird and basically, mod unfocuses from screen before unpressed actions are added to vnc keys scheduler.
No issue on library (vernacular), it was just the mod.

**Comment by shinyhut** [comment]
Nice, I'm pleased this was resolved. Shout if you need anything else.
