### ISSUE TITLE
MS-Logon support

### ISSUE THREAD

**Issue by MichalBures77** [shinyhut/vernacular-vnc#14]
I would like to ask whether there is any plan for adding support for MS-Logon authentication. That would be a great addition.

**Comment by shinyhut** [comment]
I'll see what I can do. It doesn't seem to be formally documented anywhere, but I might be able to reverse engineer it from the UltraVNC source code.

**Comment by MichalBures77** [comment]
Thanks a lot. I am looking forward to this. Closing the issue now.

**Comment by Neustradamus** [comment]
It has been solved:
- https://github.com/shinyhut/vernacular-vnc/pull/19
