### ISSUE TITLE
unable to do the enter key action

### ISSUE THREAD

**Issue by hanumanthareddy** [shinyhut/vernacular-vnc#16]
i am using vernacular-vnc, i am unable to do enter key actions on the vnc, please find the below snippet for more information. mouse movement, mouse clicks are working as expected but when i do **Enter key actions** its not working please let me know how i can fix this .... thanks in advance

client.moveMouse(70, 390); --- working
client.click(1); --- working
**client.type(13); ---- not working**

**Comment by shinyhut** [comment]
Hi @hanumanthareddy, have you tried:

`client.type(0xff0d);`

0xff0d is the Unix keysym for the ENTER key

**Comment by shinyhut** [comment]
I'll close this for now, feel free to reopen if this is still an issue.
