### ISSUE TITLE
New version release? MS Logon authentication and better performance encoding

### ISSUE THREAD

**Issue by MichalBures77** [shinyhut/vernacular-vnc#17]
A polite question regarding your precious library: Is there a chance for a **new version** release anytime **soon**? I am looking forward to the successful implementation of MS Logon authentication. Also, a better performance encoding would be a huge plus. Thanks a lot for any feedback. Your work on this is highly appreciated.

PS: If there is anything a humble junior developer could help you with: feel free to contact me at MichalBRS2020@gmail.com

**Comment by shinyhut** [comment]
Hi @MichalBures77, no I haven't had much time for this recently, but I'll try to get back to it soon. As you say, I'll probably work on MS Logon next as I can see that would be a useful feature.

**Comment by Neustradamus** [comment]
Duplicate of:
- https://github.com/shinyhut/vernacular-vnc/issues/14

It has been solved:
- https://github.com/shinyhut/vernacular-vnc/pull/19
