### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by xorpherion** [shinyhut/vernacular-vnc#2]
Hi @shinyhut,
is it possible to add a license to the project like apache 2 or MIT?

**Comment by shinyhut** [comment]
Hi @xorpherion 
Yes I'm happy to release it under the MIT license. That's been added in [878004d](https://github.com/shinyhut/vernacular-vnc/commit/878004d028749d69525caa1dc12076b829a74023) and released as [v1.3.0](https://github.com/shinyhut/vernacular-vnc/releases/tag/v1.3.0)
