### ISSUE TITLE
Colors are mixed up when connecting to VMWare VNC

### ISSUE THREAD

**Issue by anopse** [shinyhut/vernacular-vnc#22]
Hello, first I want to say, thank you for your library, it's really helping me !
I've been using your library for few months, and had to fix some stuff for my use case, so I want to share my improvements. I'm aware maybe some of my changes are too specific to my use case, feel free to merge or not merge, my changes into your library.

First issue (I created 3 issues) :

I use the library to connect to the VNC created by VMWare Workstation (free to use if you want to try it yourself) and colors are mixed up.
I connect with `BPP_24_TRUE`, arch is x64 both on client/server-host/guest.
I tried using the demo project of the library, colors are mixed up too. Used TightVNC, colors are shown properly.

To make it work I had to changes the color shifts : https://github.com/anopse/vernacular-vnc/commit/6094794088a4bca5ed27be23a92fc94175409639

Doesn't look like an endian issue as it's not simply opposite order : your code `XRBG` -> my code `BGRX`, `X` = unused)
I don't know if it happens only on VMWare or all `BPP_24_TRUE` use cases.

Thank you again for your library !

**Comment by y2k04** [comment]
Can confirm

**Comment by y2k04** [comment]
![image](https://user-images.githubusercontent.com/29883287/232258516-57aa3da4-074a-42d2-8088-059e3a5fbc57.png)

**Comment by shinyhut** [comment]
Fixed by https://github.com/shinyhut/vernacular-vnc/pull/31 for 8bpp and 24-bpp rendering modes. I wasn't able to fix it for 16bpp (it seems to be broken in VMWare). Will release shortly.
