### ISSUE TITLE
High cpu usage waiting for next update frame

### ISSUE THREAD

**Issue by anopse** [shinyhut/vernacular-vnc#23]
Hello, first I want to say, thank you for your library, it's really helping me !
I've been using your library for few months, and had to fix some stuff for my use case, so I want to share my improvements. I'm aware maybe some of my changes are too specific to my use case, feel free to merge or not merge, my changes into your library.

Second issue (I created 3 issues) :

Profiling my application, I saw a whole thread getting busy just checking datetime. It appears that you constantly check if it's time to ask an update frame. See ClientEventHandler.java line 47

I changed this in code to make it sleep before testing again : https://github.com/anopse/vernacular-vnc/commit/471f20e4ce3b534917710e86b29b6c1d53864f59

After fixing this issue, the waiting loop became negligeable in terms of CPU usage.
The two performance issues (second and third) divided the whole CPU usage made by the library by 6 times. (In my use case when profiling)

Thank you again for your library !

**Comment by shinyhut** [comment]
Thanks! I've merged this one, I'll get to the others ASAP.
