### ISSUE TITLE
Support for VNC Server v3.3

### ISSUE THREAD

**Issue by Roshanalexander** [shinyhut/vernacular-vnc#7]
Any chances of supporting VNC server version 3.3? Thanks!

**Comment by shinyhut** [comment]
Sure, I'll give it a go.

**Comment by Roshanalexander** [comment]
Hi @shinyhut,
Thanks for your quick support. It seems I'm still having the issue. Please see the screenshot.
![Screen Shot 2020-06-21 at 1 18 29 PM](https://user-images.githubusercontent.com/6432696/85231068-3b693780-b3c2-11ea-932b-7728350fe721.png)

**Comment by shinyhut** [comment]
Hi @Roshanalexander Can you try the download again now?

**Comment by Roshanalexander** [comment]
@shinyhut 
It seems to be connecting now but as soon as the connection starts, I get different error messages. Also, I'm not able to see the screen.

![Screen Shot 2020-06-21 at 1 41 22 PM](https://user-images.githubusercontent.com/6432696/85231439-eb3fa480-b3c4-11ea-8353-5c02dd19777c.png)

![Screen Shot 2020-06-21 at 1 42 21 PM](https://user-images.githubusercontent.com/6432696/85231455-13c79e80-b3c5-11ea-92dd-f2e91d9d4c64.png)

**Comment by shinyhut** [comment]
That looks like a different issue, can you let me know what VNC server you're using and I'll investigate?

**Comment by Roshanalexander** [comment]
I'm not sure what the VNC server is. It is built into my office Canon printer. I was able to VNC into the printer using the RealVNC application. But as a developer, I wanted to create a customized VNC application with some custom options to add some functions currently not available with any VNC applications.

If you have any ideas on how to retrieve the VNC server details. Please let me know. I'll try those steps.

**Comment by Roshanalexander** [comment]
Another error this time: SocketException & also Error: Type 35

![Screen Shot 2020-06-21 at 2 15 05 PM](https://user-images.githubusercontent.com/6432696/85231961-a407e280-b3c9-11ea-9ee3-1dacbc8b51c4.png)

![Screen Shot 2020-06-21 at 2 15 38 PM](https://user-images.githubusercontent.com/6432696/85231973-b6821c00-b3c9-11ea-8d23-fcdcbe65dd52.png)

**Comment by shinyhut** [comment]
This might be hard to debug without access to that particular printer, but I'll see what I can find out. Are you authenticating with a password? Also, do any other open source VNC clients work? RealVNC supports a lot of proprietary extensions.

**Comment by Roshanalexander** [comment]
Yes, I do get a prompt to enter a password and it authenticates successfully. So far I've gotten Mac OS X's build in Screen sharing app, VNC, TightVNC, etc.

**Comment by Roshanalexander** [comment]
Hey, Looks like I got it to work like 90%. I changed the code to use BPP_24_TRUE as the color depth. Now the connection succeeds and I'm able to see and operate the screen successfully. Only issue is that there's a green overlay on the screen. Please see the screenshot.

![Screen Shot 2020-06-22 at 9 55 54 AM](https://user-images.githubusercontent.com/6432696/85296075-d586b980-b46e-11ea-8a09-35c0cb518994.png)

**Comment by shinyhut** [comment]
That almost looks like the server isn't respecting our requested pixel format (or possibly the endianness of multi-byte pixel values). Can you try this build from the [feature/server-native-pixel-format](https://github.com/shinyhut/vernacular-vnc/tree/feature/server-native-pixel-format) 
experimental branch? I've temporarily changed it to ignore the user requested pixel format, always accept the server's native format, and do the endianness conversion in the client (if necessary).

[vernacular-1.10-SNAPSHOT.jar.zip](https://github.com/shinyhut/vernacular-vnc/files/4815360/vernacular-1.10-SNAPSHOT.jar.zip)

**Comment by Roshanalexander** [comment]
I'm not getting a red color overlay.

![Screen Shot 2020-06-22 at 8 01 05 PM](https://user-images.githubusercontent.com/6432696/85346424-4d7ecf00-b4c3-11ea-8ea7-ab820b9cff5a.png)
